---
power_bill:
    pattern:  qr/Your electricity bill/
    desc:     Power Bill
    filename: get_electricity_bill( shift )
gas_bill:
    pattern:  qr/Your gas bill/
    desc:     Stinky Gas Supply
    filename: get_gas_bill( shift )
credit_card_bill:
    pattern:  qr/4514111111111111/
    desc:     Credit Card Statement
    filename: get_cc_date( shift )
# If you have two cards on one account, for example:
master_card_bill:
    pattern:
        - qr/5815111111111111/
        - qr/5814111111111234/
    desc: Mastercard Bill
    filename: get_mc_date( shift )
# To put it somewhere other than the key name:
amex_bill:
    subdir: corporate_credit_card
    pattern: qr/381312341234123/
    desc: Amex Bill
    filename: get_amex_date( shift )
# You don't have to create a subroutine.  You can instead define a regex that
# will capture the date in $1.  We use Date::Parse to parse the date, so as
# long as it's an unambiguous date that can be reasonably parsed, it'll figure
# it out.
irs_document:
    pattern: qr/SSN: 12345678/
    desc: IRS Document
    date_regex: qr{(\w+\s+\d+,\s*\d+)}
